/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PomodoroRouteImport } from './routes/pomodoro'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as IndexoldRouteImport } from './routes/indexold'
import { Route as HabitsRouteImport } from './routes/habits'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as BoardRouteImport } from './routes/board'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FinanceIndexRouteImport } from './routes/finance.index'
import { Route as FinanceTransactionsRouteImport } from './routes/finance.transactions'
import { Route as FinanceTradingRouteImport } from './routes/finance.trading'
import { Route as FinanceDebtRouteImport } from './routes/finance.debt'
import { Route as FinanceContactsRouteImport } from './routes/finance.contacts'
import { Route as FinanceBudgetsRouteImport } from './routes/finance.budgets'
import { Route as FinanceAnalyticsRouteImport } from './routes/finance.analytics'
import { Route as FinanceAccountsRouteImport } from './routes/finance.accounts'
import { Route as BookBookIdRouteImport } from './routes/book.$bookId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PomodoroRoute = PomodoroRouteImport.update({
  id: '/pomodoro',
  path: '/pomodoro',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexoldRoute = IndexoldRouteImport.update({
  id: '/indexold',
  path: '/indexold',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitsRoute = HabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceIndexRoute = FinanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceTransactionsRoute = FinanceTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceTradingRoute = FinanceTradingRouteImport.update({
  id: '/trading',
  path: '/trading',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceDebtRoute = FinanceDebtRouteImport.update({
  id: '/debt',
  path: '/debt',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceContactsRoute = FinanceContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceBudgetsRoute = FinanceBudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceAnalyticsRoute = FinanceAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceAccountsRoute = FinanceAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => FinanceRoute,
} as any)
const BookBookIdRoute = BookBookIdRouteImport.update({
  id: '/book/$bookId',
  path: '/book/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/board': typeof BoardRoute
  '/calendar': typeof CalendarRoute
  '/docs': typeof DocsRoute
  '/finance': typeof FinanceRouteWithChildren
  '/habits': typeof HabitsRoute
  '/indexold': typeof IndexoldRoute
  '/journal': typeof JournalRoute
  '/library': typeof LibraryRoute
  '/pomodoro': typeof PomodoroRoute
  '/settings': typeof SettingsRoute
  '/book/$bookId': typeof BookBookIdRoute
  '/finance/accounts': typeof FinanceAccountsRoute
  '/finance/analytics': typeof FinanceAnalyticsRoute
  '/finance/budgets': typeof FinanceBudgetsRoute
  '/finance/contacts': typeof FinanceContactsRoute
  '/finance/debt': typeof FinanceDebtRoute
  '/finance/trading': typeof FinanceTradingRoute
  '/finance/transactions': typeof FinanceTransactionsRoute
  '/finance/': typeof FinanceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/board': typeof BoardRoute
  '/calendar': typeof CalendarRoute
  '/docs': typeof DocsRoute
  '/habits': typeof HabitsRoute
  '/indexold': typeof IndexoldRoute
  '/journal': typeof JournalRoute
  '/library': typeof LibraryRoute
  '/pomodoro': typeof PomodoroRoute
  '/settings': typeof SettingsRoute
  '/book/$bookId': typeof BookBookIdRoute
  '/finance/accounts': typeof FinanceAccountsRoute
  '/finance/analytics': typeof FinanceAnalyticsRoute
  '/finance/budgets': typeof FinanceBudgetsRoute
  '/finance/contacts': typeof FinanceContactsRoute
  '/finance/debt': typeof FinanceDebtRoute
  '/finance/trading': typeof FinanceTradingRoute
  '/finance/transactions': typeof FinanceTransactionsRoute
  '/finance': typeof FinanceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/board': typeof BoardRoute
  '/calendar': typeof CalendarRoute
  '/docs': typeof DocsRoute
  '/finance': typeof FinanceRouteWithChildren
  '/habits': typeof HabitsRoute
  '/indexold': typeof IndexoldRoute
  '/journal': typeof JournalRoute
  '/library': typeof LibraryRoute
  '/pomodoro': typeof PomodoroRoute
  '/settings': typeof SettingsRoute
  '/book/$bookId': typeof BookBookIdRoute
  '/finance/accounts': typeof FinanceAccountsRoute
  '/finance/analytics': typeof FinanceAnalyticsRoute
  '/finance/budgets': typeof FinanceBudgetsRoute
  '/finance/contacts': typeof FinanceContactsRoute
  '/finance/debt': typeof FinanceDebtRoute
  '/finance/trading': typeof FinanceTradingRoute
  '/finance/transactions': typeof FinanceTransactionsRoute
  '/finance/': typeof FinanceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/board'
    | '/calendar'
    | '/docs'
    | '/finance'
    | '/habits'
    | '/indexold'
    | '/journal'
    | '/library'
    | '/pomodoro'
    | '/settings'
    | '/book/$bookId'
    | '/finance/accounts'
    | '/finance/analytics'
    | '/finance/budgets'
    | '/finance/contacts'
    | '/finance/debt'
    | '/finance/trading'
    | '/finance/transactions'
    | '/finance/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/board'
    | '/calendar'
    | '/docs'
    | '/habits'
    | '/indexold'
    | '/journal'
    | '/library'
    | '/pomodoro'
    | '/settings'
    | '/book/$bookId'
    | '/finance/accounts'
    | '/finance/analytics'
    | '/finance/budgets'
    | '/finance/contacts'
    | '/finance/debt'
    | '/finance/trading'
    | '/finance/transactions'
    | '/finance'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/board'
    | '/calendar'
    | '/docs'
    | '/finance'
    | '/habits'
    | '/indexold'
    | '/journal'
    | '/library'
    | '/pomodoro'
    | '/settings'
    | '/book/$bookId'
    | '/finance/accounts'
    | '/finance/analytics'
    | '/finance/budgets'
    | '/finance/contacts'
    | '/finance/debt'
    | '/finance/trading'
    | '/finance/transactions'
    | '/finance/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BoardRoute: typeof BoardRoute
  CalendarRoute: typeof CalendarRoute
  DocsRoute: typeof DocsRoute
  FinanceRoute: typeof FinanceRouteWithChildren
  HabitsRoute: typeof HabitsRoute
  IndexoldRoute: typeof IndexoldRoute
  JournalRoute: typeof JournalRoute
  LibraryRoute: typeof LibraryRoute
  PomodoroRoute: typeof PomodoroRoute
  SettingsRoute: typeof SettingsRoute
  BookBookIdRoute: typeof BookBookIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pomodoro': {
      id: '/pomodoro'
      path: '/pomodoro'
      fullPath: '/pomodoro'
      preLoaderRoute: typeof PomodoroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indexold': {
      id: '/indexold'
      path: '/indexold'
      fullPath: '/indexold'
      preLoaderRoute: typeof IndexoldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habits': {
      id: '/habits'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof HabitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/': {
      id: '/finance/'
      path: '/'
      fullPath: '/finance/'
      preLoaderRoute: typeof FinanceIndexRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/transactions': {
      id: '/finance/transactions'
      path: '/transactions'
      fullPath: '/finance/transactions'
      preLoaderRoute: typeof FinanceTransactionsRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/trading': {
      id: '/finance/trading'
      path: '/trading'
      fullPath: '/finance/trading'
      preLoaderRoute: typeof FinanceTradingRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/debt': {
      id: '/finance/debt'
      path: '/debt'
      fullPath: '/finance/debt'
      preLoaderRoute: typeof FinanceDebtRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/contacts': {
      id: '/finance/contacts'
      path: '/contacts'
      fullPath: '/finance/contacts'
      preLoaderRoute: typeof FinanceContactsRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/budgets': {
      id: '/finance/budgets'
      path: '/budgets'
      fullPath: '/finance/budgets'
      preLoaderRoute: typeof FinanceBudgetsRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/analytics': {
      id: '/finance/analytics'
      path: '/analytics'
      fullPath: '/finance/analytics'
      preLoaderRoute: typeof FinanceAnalyticsRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/accounts': {
      id: '/finance/accounts'
      path: '/accounts'
      fullPath: '/finance/accounts'
      preLoaderRoute: typeof FinanceAccountsRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/book/$bookId': {
      id: '/book/$bookId'
      path: '/book/$bookId'
      fullPath: '/book/$bookId'
      preLoaderRoute: typeof BookBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface FinanceRouteChildren {
  FinanceAccountsRoute: typeof FinanceAccountsRoute
  FinanceAnalyticsRoute: typeof FinanceAnalyticsRoute
  FinanceBudgetsRoute: typeof FinanceBudgetsRoute
  FinanceContactsRoute: typeof FinanceContactsRoute
  FinanceDebtRoute: typeof FinanceDebtRoute
  FinanceTradingRoute: typeof FinanceTradingRoute
  FinanceTransactionsRoute: typeof FinanceTransactionsRoute
  FinanceIndexRoute: typeof FinanceIndexRoute
}

const FinanceRouteChildren: FinanceRouteChildren = {
  FinanceAccountsRoute: FinanceAccountsRoute,
  FinanceAnalyticsRoute: FinanceAnalyticsRoute,
  FinanceBudgetsRoute: FinanceBudgetsRoute,
  FinanceContactsRoute: FinanceContactsRoute,
  FinanceDebtRoute: FinanceDebtRoute,
  FinanceTradingRoute: FinanceTradingRoute,
  FinanceTransactionsRoute: FinanceTransactionsRoute,
  FinanceIndexRoute: FinanceIndexRoute,
}

const FinanceRouteWithChildren =
  FinanceRoute._addFileChildren(FinanceRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  BoardRoute: BoardRoute,
  CalendarRoute: CalendarRoute,
  DocsRoute: DocsRoute,
  FinanceRoute: FinanceRouteWithChildren,
  HabitsRoute: HabitsRoute,
  IndexoldRoute: IndexoldRoute,
  JournalRoute: JournalRoute,
  LibraryRoute: LibraryRoute,
  PomodoroRoute: PomodoroRoute,
  SettingsRoute: SettingsRoute,
  BookBookIdRoute: BookBookIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
